### ISSUE TITLE
Research (2)

### ISSUE THREAD

**Issue by MinhTuongLe20110280** [MinhTuongLe20110280/video-editing_Nhom17#11]
Tìm hiểu sơ bộ về lớp model của project

**Comment by lamnguyen0602** [comment]
Ngày 15/03: Tìm hiểu sơ bộ về những model của dự án
Gồm 2 thư mục lớn chính là Collection và InputModel
	Collection:
		Action: Id, Name, Description, Status
		AppUser: FullName
		Gallery: Id, Username, Event, file_name, Type, Width, Height	
		HightlightVideo: Id, MatchId, Username, Description, mp4, ts, Status, StatusMerge, list_mp4, list_ts
		MatchInfo: TournamentId, Username, TournametName, MatchName, MactchTime, Channel, Ip, Port, IsUploadJsonFile, JsonFile
		TagEvent: Id, UserName, Tag
		TeamOfLeague: Id, TournamentId, UserName, Team
		Tournament: Id, Name, Description
		VideoResource: PublicId, Duration, Name, Url
	InputModel:
		Youtube:
			OAuthUserCredential: project_id, client_id, client_secret, auth_uri, token_uri, redirect_uris
			ShareListInput: Id, VideoUr, VideoInfo
			Token: access_token, token_type, expires_in, refresh_token, scope
			VideoUploadModel: Credential, Title, Description, UrlVideo, Tags, Privacy
		AccountModel: Id, Username, FullName, Email, Password
		ConcatModel: MatchId, Description, JsonFile, aspect_ratio, resolution, bitrate
		ConcatResultModel: mp4, ts
		GalleryInput: EventName, File, Type, Height, Width
		HighlightFilterByTagRequest: DateFrom, DateTo, TagName, TournamentId, Teams
		InputAddEventAndLogo: eventName, File, position
		InputMergeHL: Description, Event, Logo, aspect_ratio, resolution, bitrate
		InputSendServer: Event, match_name, league, teams, match_date, IP, score, outfolder, inforder, mp4folder, aspect_ratio, resolution, bitrate, merge, logo
		MergeQueueInput: JsonFile, IdHiglight, Status, Username
		ShareModel: Cercredentials, Title, Description, Tag
		TrimVideoHightlightModel: PublicId, StartTime, EndTime
		UserConnection: Username, Room

**Comment by lamnguyen0602** [comment]
Ngày 16/03/2023
Tìm hiểu các chức năng trong project
Review và chỉnh sửa (nếu cần ) về phần Tìm hiểu các chức năng trong project Phía User và Video Editing
