### ISSUE TITLE
Setup code/framework

### ISSUE THREAD

**Issue by MinhTuongLe20110280** [MinhTuongLe20110280/video-editing_Nhom17#12]

**Comment by chhinhua2** [comment]
# Clone and Run successfully client app
# Signup new account and add more Picture and Video


![Image](https://user-images.githubusercontent.com/127853066/226189614-b7a6fa44-ed03-4335-ae13-9b2a060ed216.png)

**Comment by chhinhua2** [comment]
# Backend: ASP.NET 

- Mở được project
- Khó khăn: chưa chạy thành công backend do gặp các lỗi config chưa ffix được: Docker + Mongodb + Key
![image](https://user-images.githubusercontent.com/127853066/226383466-3ae9b874-2f3f-47cd-b4b6-e80f4e0a286f.png)
