### ISSUE TITLE
Finish Running The Code

### ISSUE THREAD

**Issue by MinhTuongLe20110280** [MinhTuongLe20110280/video-editing_Nhom17#15]

**Comment by chhinhua2** [comment]
### 22/03/2023 - Thiết lập môi trường

1. Cài đặt nodejs
   - Vào trang chủ Node.js cài đặt tại [link](https://nodejs.org/en)
   - Sau khi cài đặt xong, kiểm tra trên terminal 
     
        ![image](https://user-images.githubusercontent.com/127853066/227992586-ddb3ddc0-4297-4816-a7ed-d2f1a9977ab1.png)

**Comment by chhinhua2** [comment]
### 23/03/2023 - Thiết lập môi trường
1. Cài đặt .NET framework (version 5.0)
    - Vào trang chủ .NET cài đặt tại [link](https://dotnet.microsoft.com/en-us/download/dotnet/5.0)
    - Sau khi cài đặt xong, kiểm tra trên terminal có cài đặt thành công hay chưa
    
        ![image](https://user-images.githubusercontent.com/127853066/227994610-e4e288bb-7411-47c2-bbad-92771415d239.png)

**Comment by chhinhua2** [comment]
### 24/3/2023 - Thiết lập môi trường
1. Cài đặt MongoDB
   - Vào trang chủ MongoDB cài đặt tại [link](https://www.mongodb.com/docs/manual/installation/)
   - Kiểm tra sau khi cài đặt thành công
     
      ![image](https://user-images.githubusercontent.com/127853066/227996861-f5f44ff4-26e3-47f7-8153-d93f4c172bd1.png)

**Comment by chhinhua2** [comment]
### 27/3/2023 - Test chức năng
1. Thao tác với Gallery
   
     ![image](https://user-images.githubusercontent.com/127853066/228003791-ed32dc2b-8fd7-425d-a12b-9e79e2cb3cf8.png)


   - Thực hiện thêm một video mới:
        
   - Nhấn nút dấu cộng ở bên góc dưới phải màn hình
         
           
     ![image](https://user-images.githubusercontent.com/127853066/228005158-4451c8b1-8125-4bda-a508-5f9e68297963.png)


   - Nhập thông tin và chọn một video từ máy tính sau đó nhấn upload
         
     ![image](https://user-images.githubusercontent.com/127853066/228004789-9b1f9ce7-b9bd-4e81-84c5-d714d30ce4ae.png)

    - Sau khi up thành công
            
     ![image](https://user-images.githubusercontent.com/127853066/228005520-dc245caa-67a8-4840-8d57-bdffbd558e94.png)

**Comment by chhinhua2** [comment]
### 28/3/2023 - Chạy docker + test tính năng thêm highlight
1. Chạy docker
   - Chạy lệnh trên termianl
     ``` 
     docker-compose up
     ```
    - Kết quả chạy thành công
         
      ![image](https://user-images.githubusercontent.com/127853066/228166531-fe3e159f-1b61-4666-ad5e-f22c9e60098a.png)
     
      ![image](https://user-images.githubusercontent.com/127853066/228166714-e892ef64-3f09-4d47-8b41-9647e5a9da97.png)
          
      ![image](https://user-images.githubusercontent.com/127853066/228166756-8c8c9b6e-7b69-4b97-810e-f208f47a6196.png)

     - Test chức năng thêm highligh:   
      
       ![image](https://user-images.githubusercontent.com/127853066/228167050-ff42000c-cf72-4c2a-87d9-2ea29be1ab8e.png)
