### ISSUE TITLE
Draw Activity Diagram

### ISSUE THREAD

**Issue by MinhTuongLe20110280** [MinhTuongLe20110280/video-editing_Nhom17#18]

**Comment by lamhieo02** [comment]
Danh sách các Activity Diagram đã hoàn thành trong 1 tuần:
[Lược đồ hoạt động chức năng đăng nhập]
[Lược đồ hoạt động chức năng đăng ký]
[Lược đồ hoạt động chức năng đăng xuất]
[Lược đồ hoạt động chức năng thêm trận đấu]
[Lược đồ hoạt động chức năng xóa trận đấu]
[Lược đồ hoạt động chức năng tải lên tập tin json cho trận đấu]
[Lược đồ hoạt động chức năng lọc thông tin trận đấu]
[Lược đồ hoạt động chức năng tìm kiếm trận đấu]
[Lược đồ hoạt động chức năng xử lý đánh dấu để cắt ghép]
[Lược đồ hoạt động chức năng thêm video khi xử lý video]
[Lược đồ hoạt động chức năng thêm hình ảnh vào video]
[Lược đồ hoạt động chức năng tải lên hình ảnh, video]
[Lược đồ hoạt động chức năng xóa hình ảnh, video]
[Lược đồ hoạt động chức năng lọc, tìm kiếm video]
[Lược đồ hoạt động chức năng tải video]
[Lược đồ hoạt động chức năng chia sẻ video]
link docs chứa hình ảnh các diagram: https://docs.google.com/document/d/1Xm5HRJnU8bmdbrRWI22_lJ8KtgCkSKHm2I44Agw0hg0/edit
