### ISSUE TITLE
Draw Usecase Diagram

### ISSUE THREAD

**Issue by MinhTuongLe20110280** [MinhTuongLe20110280/video-editing_Nhom17#20]

**Comment by chhinhua2** [comment]
### Ngày 29/03/2023

TÌM HIỂU VÀ VẼ MÔ PHỎNG SƠ ĐỒ TỔNG QUAN CỦA DỰ ÁN

👉📝 [Link documentation](https://docs.google.com/document/d/1MOZDPCd95lQF2Rh2D8rZ_YXOGv9Hn8bp4YM3ufs-dVg/edit)

**Comment by chhinhua2** [comment]
### Ngày 30/03/2023

TÌM HIỂU VÀ VẼ MÔ PHỎNG SƠ ĐỒ TỔNG QUAN CỦA DỰ ÁN

👉📝 [Link documentation](https://docs.google.com/document/d/1eMCIhSnm21vKk_wIzrWtOq7e7TF-5mY2zXuhW-CkYM8/edit)

**Comment by chhinhua2** [comment]
### Ngày 31/03/2023

LIỆT KÊ & MÔ TẢ DANH SÁCH CÁC CHỨC NĂNG TRONG DỰ ÁN

👉📝 [Link documentation](https://docs.google.com/document/d/16iK7dwOo_WDu0ubyF02dQt9wStmgKJUKuTLbst-OuCo/edit)

**Comment by chhinhua2** [comment]
### Ngày 01/04/2023

LIỆT KÊ CÁC YÊU CẦU PHI CHỨC NĂNG, CÁC GIẢ THUYẾT RÀNG BUỘC VÀ RỦI RO TRONG DỰ ÁN

👉📝 [Link documentation](https://docs.google.com/document/d/1tvLzqOMisQ4W3l6LMnoTvDDWNC8iTffa3bRemduxKAA/edit)

**Comment by chhinhua2** [comment]
### Ngày 02/04/2023

LIỆT KÊ CÁC  GIẢ THUYẾT RÀNG BUỘC VÀ RỦI RO TRONG DỰ ÁN

👉📝 [Link documentation](https://docs.google.com/document/d/1TFIiXwD7-qsKEDu5O0UiQs6bWIy5H7yb3WSFGR2Xtvk/edit)

**Comment by chhinhua2** [comment]
### Ngày 03/04/2023

LIỆT KÊ & MÔ TẢ CÁC GIAO DIỆN CÓ TRONG DỰ ÁN (P1)

👉📝 [Link documentation](https://docs.google.com/document/d/1tpTMQv9W89kgjP9lIzrRcsWrR6TaFZga_12vTfKrB4s/edit)

**Comment by chhinhua2** [comment]
### Ngày 04/04/2023

LIỆT KÊ & MÔ TẢ CÁC GIAO DIỆN CÓ TRONG DỰ ÁN (P2)

👉📝 [Link documentation](https://docs.google.com/document/d/16Y94ABWxv1tbDFVYfY6Ivaj2ujriqdcolBgp3nRt7ZA/edit)
