### ISSUE TITLE
Test API on Swagger

### ISSUE THREAD

**Issue by MinhTuongLe20110280** [MinhTuongLe20110280/video-editing_Nhom17#22]

**Comment by chhinhua2** [comment]
### Ngày 5/4/2023

TÌM HIỂU VỀ CẤU TRÚC DỰ ÁN BACKEND VÀ FIX LỖI MAP API

👉📝 [Link documentation](https://docs.google.com/document/d/1MOZDPCd95lQF2Rh2D8rZ_YXOGv9Hn8bp4YM3ufs-dVg/edit)

**Comment by chhinhua2** [comment]
### Ngày 6/4/2023

TÌM HIỂU VỀ CẤU TRÚC DỰ ÁN FRONTEND VÀ FIX LỖI MAP API

👉📝 [Link documentation](https://docs.google.com/document/d/1MOZDPCd95lQF2Rh2D8rZ_YXOGv9Hn8bp4YM3ufs-dVg/edit)

**Comment by chhinhua2** [comment]
### Ngày 8/4/2023

FIX LỖI SECURITY (JWT)

👉📝 [Link documentation](https://docs.google.com/document/d/1MOZDPCd95lQF2Rh2D8rZ_YXOGv9Hn8bp4YM3ufs-dVg/edit)

**Comment by chhinhua2** [comment]
### Ngày 9/4/2023

TEST CHỨC NĂNG TRÊN FRONTEND (UI)

👉📝 [Link documentation](https://docs.google.com/document/d/1MOZDPCd95lQF2Rh2D8rZ_YXOGv9Hn8bp4YM3ufs-dVg/edit)

**Comment by chhinhua2** [comment]
### Ngày 10/4/2023

TÌM HIỂU VỀ DOCKER

👉📝 [Link documentation](https://docs.google.com/document/d/1MOZDPCd95lQF2Rh2D8rZ_YXOGv9Hn8bp4YM3ufs-dVg/edit)

**Comment by chhinhua2** [comment]
### Ngày 11/4/2023

TÌM HIỂU VỀ DEPLOY DOCKER VỚI AWS

👉📝 [Link documentation](https://docs.google.com/document/d/1MOZDPCd95lQF2Rh2D8rZ_YXOGv9Hn8bp4YM3ufs-dVg/edit)
