### ISSUE TITLE
Mapping API From BE to FE

### ISSUE THREAD

**Issue by MinhTuongLe20110280** [MinhTuongLe20110280/video-editing_Nhom17#23]

**Comment by lamnguyen0602** [comment]
Day 1 + 2: Tìm hiểu cách hoạt động của các chức năng và tìm cách kết nối và sửa lỗi để gọi API từ client qua server của domain user
Day 3 + 4 + 5: Tìm hiểu cách hoạt động của các chức năng và tìm cách kết nối và sửa lỗi để gọi API từ client qua server của domain video-editint
Day 6 + 7: Tìm hiểu lý thuyết về cách deploy ứng dụng bằng docker
