### ISSUE TITLE
Deploy App (2)

### ISSUE THREAD

**Issue by MinhTuongLe20110280** [MinhTuongLe20110280/video-editing_Nhom17#28]

**Comment by chhinhua2** [comment]
### Ngày 19/4/2023
### Ngày 20/4/2023
### Ngày 21/4/2023

Tìm hiểu về Docker và cách sử dụng

👉📝 [Link documentation](https://docs.google.com/document/d/1VI6iK-LFuUv7u_DVwHN_s-iKfoG-or_xw0bo8w0GMRc/edit?usp=sharing)

**Comment by chhinhua2** [comment]
### Ngày 22/4/2023
### Ngày 23/4/2023

-------------------------------------------------------------------------------

## Tìm hiểu về Dịch vụ AWS (Amazon Web Service) và cách sử dụng

👉📝 [Link documentation](https://docs.google.com/document/d/1ULC8CHp9KV0zR6Ivyy6tjm1uza19frOCHqsFc48dkBk/edit?usp=sharing)

**Comment by chhinhua2** [comment]
### Ngày 25/4/2023

-------------------------------------------------------------------------------

## Build project & deploy on AWS with Docker
👉📝 [Link documentation](https://docs.google.com/document/d/1WU6mQbmLAk7SWDmWNnEFztJRlZhoJxYfsGMNDr3L8-c/edit?usp=sharing)
