### ISSUE TITLE
Deploy App (3)

### ISSUE THREAD

**Issue by MinhTuongLe20110280** [MinhTuongLe20110280/video-editing_Nhom17#29]

**Comment by lamhieo02** [comment]
Build & deploy application on aws using Docker



Build app with Dockerfile
Dockerfile:

File Dockerfile sử dụng một base image của ASP.NET 5.0 (mcr.microsoft.com/dotnet/aspnet:5.0) để tạo một image.

Các bước trong Dockerfile của bạn như sau:

1. Bước đầu tiên tạo một base image và thiết lập thư mục làm việc của container là /app. Container sẽ lắng nghe các kết nối đến cổng 80 và 443.



2. Tiếp theo, Dockerfile tiếp tục tạo một build image và thiết lập thư mục làm việc của build là /src. Dockerfile copy file video-editing-api.csproj từ thư mục video-editing-api/ vào container và sử dụng dotnet restore để tải xuống các gói NuGet cần thiết cho dự án.



3. Sau đó, Dockerfile copy toàn bộ nội dung của dự án vào container và thiết lập thư mục làm việc của container là video-editing-api/. Tiếp theo, Dockerfile sử dụng dotnet build để build dự án với chế độ Release và đầu ra là thư mục /app/build.



4. Bước tiếp theo tạo một publish image và sử dụng dotnet publish để tạo các file output của dự án vào thư mục /app/publish.


5. Cuối cùng, Dockerfile tạo một image cuối cùng sử dụng base image ở bước 1 và copy các file output của dự án từ publish image vào thư mục /app của container. ENTRYPOINT của image là dotnet video-editing-api.dll để start ứng dụng của bạn.



Build images
 	Gõ lệnh
		
sau khi build xong gõ lệnh “docker images” để xem các image:

Hoặc có thể xem trong docker desktop:


2. Deploy lên AWS ECR (Elastic Container Registry)
đăng nhập vào aws và vào ECR tạo một repo và đặt tên là “video-editing-api”:

bấm create repository và đặt tên:


chọn create repository

sau khi tạo thành công nó sẽ hiện như sau:





b. Deploy
Bấm vào tên repo và chọn View push command:


Sao chép và chạy từng dòng command theo hướng dẫn:

	
chi tiết các bước thực hiện như sau:
	

sau khi push thành công thì ta có được Images dự án asp.net được lưu trên AWS ECR
